// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bnZmvw68OTkWDD-rGrM1BYRBcouYB9M',
    appId: '1:494171386784:web:9a766ec6df937023226ac5',
    messagingSenderId: '494171386784',
    projectId: 'alu-internship-b223c',
    authDomain: 'alu-internship-b223c.firebaseapp.com',
    storageBucket: 'alu-internship-b223c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuluXWZ-MxUzdJyrEA-ytempV5ZVZQdxc',
    appId: '1:494171386784:android:2feb14f316ff401c226ac5',
    messagingSenderId: '494171386784',
    projectId: 'alu-internship-b223c',
    storageBucket: 'alu-internship-b223c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxrOpUZzYXBJT7Rmj54wxVUFYqITDNqrc',
    appId: '1:494171386784:ios:ad688e3965c62d76226ac5',
    messagingSenderId: '494171386784',
    projectId: 'alu-internship-b223c',
    storageBucket: 'alu-internship-b223c.firebasestorage.app',
    iosBundleId: 'com.example.aluInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxrOpUZzYXBJT7Rmj54wxVUFYqITDNqrc',
    appId: '1:494171386784:ios:ad688e3965c62d76226ac5',
    messagingSenderId: '494171386784',
    projectId: 'alu-internship-b223c',
    storageBucket: 'alu-internship-b223c.firebasestorage.app',
    iosBundleId: 'com.example.aluInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bnZmvw68OTkWDD-rGrM1BYRBcouYB9M',
    appId: '1:494171386784:web:051a2425d5793f6d226ac5',
    messagingSenderId: '494171386784',
    projectId: 'alu-internship-b223c',
    authDomain: 'alu-internship-b223c.firebaseapp.com',
    storageBucket: 'alu-internship-b223c.firebasestorage.app',
  );
}